"""Add date column in Articles

Revision ID: 33f7ad2fee6b
Revises: ca45d7c3946
Create Date: 2016-06-03 12:55:09.925418

"""

# revision identifiers, used by Alembic.
revision = '33f7ad2fee6b'
down_revision = 'ca45d7c3946'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('date', sa.DATE(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'date')
    ### end Alembic commands ###
