"""empty message

Revision ID: 43527128aadb
Revises: None
Create Date: 2016-06-08 20:46:13.005657

"""

# revision identifiers, used by Alembic.
revision = '43527128aadb'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
