"""empty message

Revision ID: 5aa9611ecc1b
Revises: None
Create Date: 2016-06-08 20:32:17.672425

"""

# revision identifiers, used by Alembic.
revision = '5aa9611ecc1b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
